### ISSUE TITLE
Document if sweet expressions can be used in REPL

### ISSUE THREAD

**Issue by logc** [takikawa/sweet-racket#29]
This is not an issue but a feature request.  Or a question. :smile:

If it is possible to load the package at startup in the Racket REPL, (like Typed Racket can be loaded via `racket -I typed/racket`), then this should be mentioned in the startup documentation.

Thanks!

**Comment by AlexKnauth** [comment]
Now if you update, you should be able to do `racket -I sweet-exp/racket/init.rkt`.

**Comment by logc** [comment]
Thanks!  It worked after an upgrade.

For the benefit of others, I guess this should be mentioned in the documentation as well. Don't you think?

**Comment by AlexKnauth** [comment]
@takikawa 
What do you think?
I don't have much experience with the racket repl on the command-line or the racket command in general because I mostly use DrRacket instead, so I'm not sure.

**Comment by GReagle** [comment]
Yes of course if the sweet expressions can be used in the REPL it should be documented.  I can't imagine why not.

**Comment by logc** [comment]
After six years of this request, I think it can be considered rejected. The solution proposed did work, and this issue itself is some sort of documentation for interested readers.
